import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { DataSeeder } from "@/components/common/DataSeeder";
import "./globals.css";
import { Agentation } from "agentation";
import { Header } from "@/components/common";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="pt-14">
        {process.env.NODE_ENV === "development" && <Agentation />}
        <DataSeeder />
        <Header /> 
        {children}
      </body>
    </html>
  );
}
